- name: Run docker-compose ps remotely
  hosts: nodes
  become: yes
  become_user: root
  remote_user: centos
  tasks:
    - name: Execute docker-compose ps
      shell: docker-compose -f /opt/stack/docker-compose.yaml ps
      args:
        chdir: /opt/stack/
      register: docker_compose_ps_output

    - name: Parse docker-compose ps output
      shell: echo "{{ docker_compose_ps_output.stdout }}"
      register: parsed_output

    - debug:
        var: parsed_output.stdout_lines