# -*- mode: ruby -*-

#  arm64 - шоб вообще взлетело на чипе M1
ISO = "bento/ubuntu-20.04-arm64"
NET = "192.168.56."
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "../ansible/inventory"

servers = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
    #        шоб сеть зaвелась
      node.vm.usable_port_range = (2200..2250)
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      #        шоб сеть зaвелась
      node.vm.network "private_network", ip: machine[:ip], virtualbox__intnet: "intnet"
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.provider :vmware_desktop do |vm|
      #        адаптация кофигов под VmWare
        vm.vmx["memsize"] = machine[:ram]
        vm.vmx["numvcpus"] = machine[:core]
        vm.vmx['displayname'] = machine[:hostname]
      end
      node.vm.provision "ansible" do |setup|
        setup.compatibility_mode = "2.0"
#        шоб ансибл завелся
        setup.inventory_path = INVENTORY_PATH
        setup.playbook = "../ansible/provision.yml"
        setup.become = true
        setup.extra_vars = { ansible_user: 'vagrant' }
      end
    end
  end
end
